#!/usr/bin/env bash
set -euo pipefail

# One command runner for local/server use.
# Keeps production-safe defaults and supports optional single-episode mode.
#
# Examples:
#   bash run_one_command.sh
#   EPISODE_ID=68d3110528e87fa66804713c bash run_one_command.sh

CONFIG="${CONFIG:-sample_web_auto_solver_production.yaml}"
REMOTE="${REMOTE:-gdrive}"
STRICT_GATE="${STRICT_GATE:-1}"
REQUIRE_TIER2="${REQUIRE_TIER2:-0}"
PASS_SCORE_THRESHOLD="${PASS_SCORE_THRESHOLD:-95}"
RESUME_ONLY="${RESUME_ONLY:-1}"
AUTO_BUILD_CONTEXT_PACK="${AUTO_BUILD_CONTEXT_PACK:-1}"
FORCE_REGENERATE="${FORCE_REGENERATE:-0}"
EPISODE_ID="${EPISODE_ID:-}"
DRIVE_LINK="${DRIVE_LINK:-}"
KNOWLEDGE_UPDATE="${KNOWLEDGE_UPDATE:-0}"
DISCORD_JSON="${DISCORD_JSON:-}"
WHATSAPP_TXT="${WHATSAPP_TXT:-}"

CONFIG="$CONFIG" \
REMOTE="$REMOTE" \
STRICT_GATE="$STRICT_GATE" \
REQUIRE_TIER2="$REQUIRE_TIER2" \
PASS_SCORE_THRESHOLD="$PASS_SCORE_THRESHOLD" \
RESUME_ONLY="$RESUME_ONLY" \
AUTO_BUILD_CONTEXT_PACK="$AUTO_BUILD_CONTEXT_PACK" \
FORCE_REGENERATE="$FORCE_REGENERATE" \
EPISODE_ID="$EPISODE_ID" \
DRIVE_LINK="$DRIVE_LINK" \
KNOWLEDGE_UPDATE="$KNOWLEDGE_UPDATE" \
DISCORD_JSON="$DISCORD_JSON" \
WHATSAPP_TXT="$WHATSAPP_TXT" \
bash ./run_production.sh
